<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>319c7d0f-d4d4-4d17-b218-417cf10d53c8</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Application\Services\" />
    <Folder Include="Domain\Images\" />
    <Folder Include="Domain\Intefraces\" />
    <Folder Include="Infrastructure\Data\" />
    <Folder Include="Infrastructure\Repositories\" />
    <Folder Include="Tests\" />
  </ItemGroup>

</Project>
